nacos-host: 192.168.2.222
spring:
  application:
    name: base-service
  profiles:
    active: template
  cloud:
    nacos:
      ## 注册中心配置
      discovery:
        server-addr: ${nacos-host}:8848
        namespace: public
        group: DEFAULT_GROUP
        enabled: true
