host: 192.168.2.222
server:
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
  port: 9008
spring:
  rabbitmq:
    virtual-host: test
    host: ${host}
    port: 5672
    username: admin
    password: admin
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: ${host}


#    # 当exchange无法找到任何一个合适的queue时，将消息return给生产者
#    spring.rabbitmq.template.mandatory=true
#    # 必须设置为true，否则消息消息路由失败也无法触发Return回调
#    spring.rabbitmq.publisher-returns=true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  server:
    port: 8082

customize:
  es:
    hosts[0]:
      ip: 192.168.2.222
      port: 9200




