host: 192.168.2.222
server:
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
  port: 9006

mybatis-plus:
  #type-aliases-package: com.ly.*
  mapper-locations: classpath*:/com.business.auth/*/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#org.apache.ibatis.logging.log4j2.Log4j2Impl #
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://{host}:3306/t_auth?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    ## # 配置分库策略
    rules:
      sharding:
        tables.t_auth_user:
          actual-data-nodes: ds0.t_auth_user_->{1..2}
        #        tables:
        #          t_auth_user:
        #            table-strategy:
        #              standard:
        #                sharding-column: id
        #                sharding-algorithm-name: table_inline
        # 配置 分片算法
        sharding-algorithms:
          table_inline:
            type: INLINE
            props:
              algorithm-expression: t_auth_user_${id % 2}
  redis:
    host: ${host}


#    # 当exchange无法找到任何一个合适的queue时，将消息return给生产者
#    spring.rabbitmq.template.mandatory=true
#    # 必须设置为true，否则消息消息路由失败也无法触发Return回调
#    spring.rabbitmq.publisher-returns=true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  server:
    port: 8082




