server:
  port: 9999

spring:
  cloud:
    gateway:
      discovery:
        locator:
          ####开启以服务id去注册中心上获取转发地址
          enabled: true
        ###路由策略
      routes:
        #filters:
        #  - RewritePath=/admin/(?<segment>.*), /admin/$\{segment}
        - id: file-service
          ####转发http://www.mayikt.com/
          uri: lb://file-service/
          ###匹配规则
          predicates:
            - Path=/file/**
        - id: test-server
          ####转发http://www.mayikt.com/
          uri: lb://test-server
          ###匹配规则
          predicates:
            - Path=/testService/**
          filters:
            #- ## 重写路径，去掉路径的product
            - RewritePath=/testService(?<segment>/?.*), $\{segment}

logging:
  level:
    com.bussiness: debug

management:
  endpoints:
    web:
      exposure:
        include: gateway
